# @format

version: "3"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      # target: development
    restart: always
    environment:
      - TELEGRAM_TOKEN=5836158221:AAFVQc0XAjSxVTM7kuxJZdIVNL2rHSHXYLQ
      - MONGO_URI=mongodb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_USERNAME=SOME_USERNAME
      - MONGO_PASSWORD=SOME_PASSWORD
      - SUPER_ADMIN_PHONE_NUMBERS=251923772845
    env_file:
      - .env
    command: node src/app.js
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
   
      
    networks:
      - bot-network



  


networks:
  bot-network:



