# @format

version: "3"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      # target: development
    restart: always
    environment:
      - TELEGRAM_TOKEN=6053964527:AAEmm5xf4exYWy2aN5zGVZ3eMpMOFcvKEl0
      - MONGO_URI=localhost:27017/saba_bot
      - REDIS_HOST=redis://red-cjdmk4qvvtos73cono70:6379
      - REDIS_PORT=6379
      - MONGO_USERNAME=SOME_USERNAME
      - MONGO_PASSWORD=SOME_PASSWORD
      - SUPER_ADMIN_PHONE_NUMBERS=251923772845
    env_file:
      - .env
    command: node src/app.js
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    depends_on:
      - mongodb
      - redis
    networks:
      - bot-network

  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongodb-data:/data/db
    networks:
      - bot-network

  redis:
    image: redis
    restart: always
    networks:
      - bot-network

networks:
  bot-network:

volumes:
  mongodb-data:
